const traducciones = {
    es: {
      nav_sobre_mi: "Sobre mí",
      nav_habilidades: "Habilidades",
      nav_educacion: "Educación &amp; Proyectos",
      hero_role: "Desarrolladora <strong>Full Stack</strong> Junior.",
      eyebrow_sobre_mi: "Sobre mí",
      label_formacion: "formación",
      val_formacion: "Ingeniería Informática",
      label_universidad: "universidad",
      about_p1: "Soy programadora junior graduada del ciclo formativo de <strong>Desarrollo de Aplicaciones Web</strong> y actualmente me encuentro cursando el Grado en <strong>Ingeniería Informática</strong> en la Universitat Oberta de Catalunya (UOC).",
      about_p2: "Manejo herramientas y lenguajes actuales como HTML, CSS, JavaScript, PHP y frameworks como React y Vue.js. Tengo conocimientos en bases de datos como MySQL y PostgreSQL, y también manejo el control de versiones con GitHub.",
      about_p3: "Me apasiona el desarrollo web y siempre estoy buscando aprender nuevas tecnologías y mejorar mis habilidades. Además, tengo un gran interés por ampliar mis conocimientos, por lo que actualmente estoy aprendiendo programación básica en <strong>ABAP</strong>.",
      lang_es: "español:",
      lvl_native: "nativo",
      lang_ca: "catalán:",
      lvl_high: "alto",
      lang_en: "inglés:",
      lvl_intermediate: "intermedio",
      lang_th: "tailandés:",
      lvl_basic: "básico",
      eyebrow_habilidades: "Habilidades",
      cat_version_control: "Control de versiones",
      cat_learning: "En aprendizaje",
      eyebrow_contacto: "Contacto",
      contact_phone: "TELÉFONO",
      footer_next: "Educación, experiencia y proyectos →",
      nav_edu: "Educación",
      nav_exp: "Experiencia",
      nav_proj: "Proyectos",
      nav_back: "← Inicio",
      hero_title_exp: "Mi <em>camino</em> profesional",
      hero_desc_exp: "Formación, experiencia y proyectos.",
      eyebrow_edu: "Educación",
      edu_1_date: "Septiembre 2025 — Actualidad",
      edu_1_title: "Ingeniería Informática",
      edu_1_place: "Universitat Oberta de Catalunya, Barcelona, España",
      edu_1_desc: "Estudios universitarios de grado en curso.",
      edu_2_date: "Septiembre 2023 — Mayo 2025",
      edu_2_title: "Ciclo Superior de Desarrollo de Aplicaciones Web",
      edu_2_place: "Instituto Thos i Codina, Mataró, España",
      edu_2_desc: "Formación técnica especializada en programación y desarrollo web.",
      edu_3_date: "Septiembre 2021 — Mayo 2023",
      edu_3_title: "Bachillerato Tecnológico",
      edu_3_place: "Instituto Laia L'Arquera, Mataró, España",
      edu_3_desc: "Especialización en la rama de ciencias y tecnología.",
      eyebrow_exp: "Experiencia",
      exp_1_title: "Desarrolladora de Integración (SAP WM & Autostore)",
      exp_1_company: "Empresa Panameña de Alimentos",
      exp_1_li1: "Desarrollo en <strong>ABAP</strong> para la integración bidireccional entre <strong>SAP WM</strong> y el sistema automatizado <strong>Autostore</strong> mediante la creación y consumo de Web Services.",
      exp_1_li2: "Automatización de tareas logísticas: creación, procesamiento y confirmación de órdenes de transporte y orquestación de salidas.",
      exp_1_li3: "Implementación de programas y transacciones SAP para ajustes de stock y consulta de inventario en tiempo real.",
      exp_1_li4: "Soporte técnico continuo, mantenimiento de canales de comunicación y procesamiento de mensajería para asegurar la integridad de los datos transaccionales.",
      exp_2_title: "Prácticas laborales en una empresa de software",
      exp_2_date: "Ene 2025 — Jun 2025",
      exp_2_company: "TellMeBye, Mataró, España",
      exp_2_li1: "Colaboración y soporte en el desarrollo y mantenimiento de aplicaciones.",
      exp_2_li2: "Adquisición de experiencia práctica en un entorno de trabajo real y uso de tecnologías del sector.",
      eyebrow_proj: "Proyectos",
      proj_1_title: "API de Microservicios",
      proj_1_desc: "API RESTful con arquitectura de microservicios. Soporta autenticación JWT, gestión de eventos, tickets en PDF, exportación XML y administración de usuarios, asientos y compras.",
      proj_2_title: "Generador de Entradas PDF",
      proj_2_desc: "Aplicación para generar entradas en formato PDF con diseño visual, código QR y código de barras utilizando mPDF, QR Code Generator y Barcode Generator.",
      proj_3_title: "Gestión de Frases Célebres",
      proj_3_desc: "Aplicación web MVC con Doctrine ORM. Permite gestionar frases célebres, autores y temas con CRUD, buscador, paginación, y enrutamiento dinámico mediante FrontController.",
      proj_4_title: "Gestión de Frases + Landing Page",
      proj_4_desc: "App MVC que gestiona frases y autores. Incluye landing page con eventos, contacto, carga de datos XML y análisis de inversiones conectando con Inversis mediante PDO/MySQLi.",
      proj_5_title: "Chat en Red Local",
      proj_5_desc: "Aplicación de chat para aula con interfaz gráfica en Java (JFrame) y MySQL. Usa procedimientos almacenados, arquitectura MVC, control de acceso y mensajes en tiempo real.",
      proj_6_title: "Votaciones Municipales DB4O",
      proj_6_desc: "App Java (Swing) que importa datos electorales desde CSV y los almacena en DB4O. Permite consultas territoriales, listados y corrección de datos con arquitectura MVC.",
      proj_7_title: "Animaciones CSS Creativas",
      proj_7_desc: "Proyecto visual con animaciones exclusivas en CSS (sin JS). Incluye escena marina, carruseles 2D/3D, zoom y efectos musicales aprovechando @keyframes, transforms y :has().",
      proj_8_title: "Interfaces con Bootstrap 5",
      proj_8_desc: "Diseño web responsivo que incluye navbar con modales, carrusel, cards, offcanvas y formularios con validación. Estilizada con SCSS y Utility API de Bootstrap.",
      proj_9_title: "Mitología Griega Accesible",
      proj_9_desc: "Página informativa inclusiva conforme a estándares WCAG. Implementa roles ARIA, navegación por teclado, contraste AAA y estructuras semánticas para lectores de pantalla.",
      proj_10_title: "Web con SASS + Modo Oscuro",
      proj_10_desc: "Página moderna responsive estilizada con SASS (SCSS). Incluye modo claro/oscuro con transición suave, mixins, variables y nesting para un código mantenible.",
      link_github: "github →",
      link_postman: "postman →",
      link_demo: "demo pdf →",
      footer_back: "← Volver al inicio",
      hero_prompt: "gabriela@sandoval:~$ cat trayectoria.log<span class=\"cursor\"></span>",
      frame_proj_1: "api-microservicios.php",
      frame_proj_2: "generador-entradas.php",
      frame_proj_3: "frases-doctrine.php",
      frame_proj_4: "landing-inversiones.php",
      frame_proj_5: "chat-red-local.java",
      frame_proj_6: "votaciones.java",
      frame_proj_7: "animaciones.css",
      frame_proj_8: "interfaz-bs5.scss",
      frame_proj_9: "accesibilidad.html",
      frame_proj_10: "dark-mode.scss",
      eyebrow_certs: "Certificaciones",
      cert_1_title: "Communicative Thai for Foreigners (Spanish version)",
      cert_1_date: "Jul 2026",
      cert_1_company: "Chulalongkorn University",
      cert_1_li1: "Finalización exitosa del curso online abierto sin créditos de tailandés básico.",
      cert_1_li2: "Credencial ID: CV1419995.",
      cert_1_link: "Certificado →"
    },
    en: {
      nav_sobre_mi: "About me",
      nav_habilidades: "Skills",
      nav_educacion: "Education &amp; Projects",
      hero_role: "<strong>Full Stack</strong> Developer Junior.",
      eyebrow_sobre_mi: "About me",
      label_formacion: "education",
      val_formacion: "Computer Engineering",
      label_universidad: "university",
      about_p1: "I am a junior programmer graduated from the <strong>Web Application Development</strong> vocational training, currently pursuing a degree in <strong>Computer Engineering</strong> at the Universitat Oberta de Catalunya (UOC).",
      about_p2: "I use modern tools and languages such as HTML, CSS, JavaScript, PHP, and frameworks like React and Vue.js. I have knowledge of databases like MySQL and PostgreSQL, and I also handle version control with GitHub.",
      about_p3: "I am passionate about web development and I am always looking to learn new technologies and improve my skills. I also have a strong interest in expanding my knowledge, which is why I am currently learning basic programming in <strong>ABAP</strong>.",
      lang_es: "spanish:",
      lvl_native: "native",
      lang_ca: "catalan:",
      lvl_high: "advanced",
      lang_en: "english:",
      lvl_intermediate: "intermediate",
      lang_th: "thai:",
      lvl_basic: "basic",
      eyebrow_habilidades: "Skills",
      cat_version_control: "Version Control",
      cat_learning: "Currently learning",
      eyebrow_contacto: "Contact",
      contact_phone: "PHONE",
      footer_next: "Education, experience and projects →",
      nav_edu: "Education",
      nav_exp: "Experience",
      nav_proj: "Projects",
      nav_back: "← Home",
      hero_title_exp: "My professional <em>path</em>",
      hero_desc_exp: "Education, experience, and projects.",
      eyebrow_edu: "Education",
      edu_1_date: "September 2025 — Present",
      edu_1_title: "Computer Engineering",
      edu_1_place: "Universitat Oberta de Catalunya, Barcelona, Spain",
      edu_1_desc: "Ongoing undergraduate university studies.",
      edu_2_date: "September 2023 — May 2025",
      edu_2_title: "Higher National Diploma in Web Application Development",
      edu_2_place: "Instituto Thos i Codina, Mataró, Spain",
      edu_2_desc: "Specialized technical training in programming and web development.",
      edu_3_date: "September 2021 — May 2023",
      edu_3_title: "Technological High School",
      edu_3_place: "Instituto Laia L'Arquera, Mataró, Spain",
      edu_3_desc: "Specialization in science and technology.",
      eyebrow_exp: "Experience",
      exp_1_title: "Integration Developer (SAP WM & Autostore)",
      exp_1_company: "Empresa Panameña de Alimentos",
      exp_1_li1: "Development in <strong>ABAP</strong> for bidirectional integration between <strong>SAP WM</strong> and the automated system <strong>Autostore</strong> through creation and consumption of Web Services.",
      exp_1_li2: "Automation of logistics tasks: creation, processing, and confirmation of transfer orders and orchestration of outbound deliveries.",
      exp_1_li3: "Implementation of SAP programs and transactions for stock adjustments and real-time inventory queries.",
      exp_1_li4: "Continuous technical support, maintenance of communication channels, and messaging processing to ensure transactional data integrity.",
      exp_2_title: "Software Company Internship",
      exp_2_date: "Jan 2025 — Jun 2025",
      exp_2_company: "TellMeBye, Mataró, Spain",
      exp_2_li1: "Collaboration and support in application development and maintenance.",
      exp_2_li2: "Acquired practical experience in a real work environment using industry technologies.",
      eyebrow_proj: "Projects",
      proj_1_title: "Microservices API",
      proj_1_desc: "RESTful API with microservices architecture. Supports JWT authentication, event management, PDF tickets, XML export, and management of users, seats, and purchases.",
      proj_2_title: "PDF Ticket Generator",
      proj_2_desc: "Application to generate PDF tickets with visual design, QR code, and barcode using mPDF, QR Code Generator, and Barcode Generator.",
      proj_3_title: "Famous Quotes Management",
      proj_3_desc: "MVC web application with Doctrine ORM. Allows managing famous quotes, authors, and topics with CRUD operations, search engine, pagination, and dynamic routing via FrontController.",
      proj_4_title: "Quotes Management + Landing Page",
      proj_4_desc: "MVC app that manages quotes and authors. Includes landing page with events, contact, XML data loading, and investment analysis connecting with Inversis via PDO/MySQLi.",
      proj_5_title: "Local Network Chat",
      proj_5_desc: "Classroom chat application with graphical interface in Java (JFrame) and MySQL. Uses stored procedures, MVC architecture, access control, and real-time messaging.",
      proj_6_title: "DB4O Municipal Elections",
      proj_6_desc: "Java App (Swing) that imports electoral data from CSV and stores it in DB4O. Allows territorial queries, listings, and data correction with MVC architecture.",
      proj_7_title: "Creative CSS Animations",
      proj_7_desc: "Visual project with exclusive CSS animations (no JS). Includes marine scene, 2D/3D carousels, zoom, and musical effects leveraging @keyframes, transforms, and :has().",
      proj_8_title: "Bootstrap 5 Interfaces",
      proj_8_desc: "Responsive web design including navbar with modals, carousel, cards, offcanvas, and forms with validation. Styled with SCSS and Bootstrap Utility API.",
      proj_9_title: "Accessible Greek Mythology",
      proj_9_desc: "Inclusive informational page compliant with WCAG standards. Implements ARIA roles, keyboard navigation, AAA contrast, and semantic structures for screen readers.",
      proj_10_title: "Web with SASS + Dark Mode",
      proj_10_desc: "Modern responsive page styled with SASS (SCSS). Includes light/dark mode with smooth transition, mixins, variables, and nesting for maintainable code.",
      link_github: "github →",
      link_postman: "postman →",
      link_demo: "demo pdf →",
      footer_back: "← Back to home",
      hero_prompt: "gabriela@sandoval:~$ cat career.log<span class=\"cursor\"></span>",
      frame_proj_1: "microservices-api.php",
      frame_proj_2: "ticket-generator.php",
      frame_proj_3: "doctrine-quotes.php",
      frame_proj_4: "investment-landing.php",
      frame_proj_5: "local-network-chat.java",
      frame_proj_6: "elections.java",
      frame_proj_7: "animations.css",
      frame_proj_8: "bs5-interface.scss",
      frame_proj_9: "accessibility.html",
      frame_proj_10: "dark-mode.scss",
      eyebrow_certs: "Certifications",
      cert_1_title: "Communicative Thai for Foreigners (Spanish version)",
      cert_1_date: "Jul 2026",
      cert_1_company: "Chulalongkorn University",
      cert_1_li1: "Successful completion of the non-credit open online course in basic Thai.",
      cert_1_li2: "Credential ID: CV1419995.",
      cert_1_link: "Certificate →"
    }
  };
  
  function cambiarIdioma(idioma) {
      localStorage.setItem('idioma', idioma);
  
      const elementos = document.querySelectorAll('[data-lang]');
      elementos.forEach((elemento) => {
          const clave = elemento.getAttribute('data-lang');
          if (traducciones[idioma][clave]) {
              elemento.innerHTML = traducciones[idioma][clave];
          }
      });
  
      document.documentElement.lang = idioma;
  }
  
  document.addEventListener('DOMContentLoaded', () => {
      const idiomaGuardado = localStorage.getItem('idioma') || 'es';
      cambiarIdioma(idiomaGuardado);
  });